# Generated by Django 4.1.7 on 2023-04-18 11:15

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Congress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("number", models.SmallIntegerField()),
                ("description", models.TextField()),
                (
                    "thumbnail",
                    models.ImageField(blank=True, null=True, upload_to="images"),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Day",
            fields=[
                (
                    "date",
                    models.CharField(max_length=24, primary_key=True, serialize=False),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Room",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("number", models.SmallIntegerField(default=1)),
                ("inprogress", models.CharField(blank=True, max_length=250)),
                (
                    "congress",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_conf_name",
                        to="planning.congress",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Session",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("order", models.SmallIntegerField(default=1)),
                (
                    "time_start",
                    models.TimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "time_end",
                    models.TimeField(blank=True, default=django.utils.timezone.now),
                ),
                (
                    "date",
                    models.ForeignKey(
                        default="self.date",
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planning.day",
                    ),
                ),
                (
                    "room",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_conf_room",
                        to="planning.room",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Presentation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250)),
                ("author", models.CharField(max_length=100)),
                ("duration", models.SmallIntegerField()),
                (
                    "session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_conf_name",
                        to="planning.session",
                    ),
                ),
            ],
        ),
    ]
