# Generated by Django 4.1.7 on 2023-09-26 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="File",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("path", models.CharField(max_length=100)),
                ("name", models.CharField(max_length=50)),
                ("eof", models.BooleanField()),
                ("on_server", models.BooleanField(default=False, null=True)),
                ("in_room", models.BooleanField(default=False, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="presentation",
            name="author",
        ),
        migrations.AddField(
            model_name="day",
            name="congress",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="confs_days",
                to="planning.congress",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="day",
            name="id",
            field=models.BigAutoField(
                auto_created=True,
                default=1,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="room",
            name="ip_server",
            field=models.CharField(default="", max_length=40),
        ),
        migrations.AlterField(
            model_name="day",
            name="date",
            field=models.CharField(max_length=24),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="duration",
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="title",
            field=models.CharField(default="", max_length=250),
        ),
        migrations.AlterField(
            model_name="session",
            name="date",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="event_day_session",
                to="planning.day",
            ),
        ),
        migrations.CreateModel(
            name="Intervenant",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=50)),
                ("prenom", models.CharField(max_length=50)),
                ("logo", models.ImageField(blank=True, null=True, upload_to="")),
                (
                    "congress",
                    models.ForeignKey(
                        default="",
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="speaker_congres",
                        to="planning.congress",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="InterPresent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "id_intervenant",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="planning.intervenant",
                    ),
                ),
                (
                    "id_presentation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="planning.presentation",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="presentation",
            name="fichier_pptx",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="planning.file",
            ),
        ),
    ]
