# Generated by Django 4.1.7 on 2023-04-25 08:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0002_day_congress"),
    ]

    operations = [
        migrations.AddField(
            model_name="congress",
            name="today",
            field=models.DateField(blank=True, default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="author",
            field=models.CharField(default="........d.....", max_length=100),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="duration",
            field=models.SmallIntegerField(default=30),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="title",
            field=models.CharField(default=".............", max_length=250),
        ),
    ]
