# Generated by Django 4.1.7 on 2023-04-25 08:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("planning", "0003_congress_today_alter_presentation_author_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="presentation",
            name="author",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AlterField(
            model_name="presentation",
            name="title",
            field=models.CharField(default="", max_length=250),
        ),
    ]
