# Generated by Django 4.1.7 on 2023-04-25 12:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0004_alter_presentation_author_alter_presentation_title'),
    ]

    operations = [
        migrations.CreateModel(
            name='Intervenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=50)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='')),
            ],
        ),
        migrations.RemoveField(
            model_name='congress',
            name='today',
        ),
        migrations.AlterField(
            model_name='presentation',
            name='author',
            field=models.CharField(default='........d.....', max_length=100),
        ),
        migrations.AlterField(
            model_name='presentation',
            name='title',
            field=models.CharField(default='.............', max_length=250),
        ),
        migrations.CreateModel(
            name='InterPresent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_intervenant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='planning.intervenant')),
                ('id_presentation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='planning.presentation')),
            ],
        ),
    ]
