# Generated by Django 4.1.7 on 2023-04-25 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0005_intervenant_remove_congress_today_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presentation',
            name='author',
        ),
    ]
