# Generated by Django 4.1.7 on 2023-05-04 08:41

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0006_remove_presentation_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='presentation',
            name='fichier_pptx',
            field=models.FileField(null=True, upload_to='preview/media/documents', validators=[django.core.validators.FileExtensionValidator(['pptx'])]),
        ),
    ]
