# Generated by Django 4.1.7 on 2023-07-26 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0010_file_alter_presentation_fichier_pptx'),
    ]

    operations = [
        migrations.AddField(
            model_name='file',
            name='in_room',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='file',
            name='on_server',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
