# Generated by Django 4.1.7 on 2023-06-26 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0011_file_in_room_file_on_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='file',
            name='in_room',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='file',
            name='on_server',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
