# Generated by Django 4.1.7 on 2023-07-12 15:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_alter_file_in_room_alter_file_on_server'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presentation',
            name='fichier_pptx',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='planning.file'),
        ),
    ]
