# Generated by Django 4.1.7 on 2023-07-19 09:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0012_alter_file_in_room_alter_file_on_server'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='ip_pc',
            field=models.CharField(blank=True, default='127.0.0.1', max_length=250),
        ),
    ]
