# Generated by Django 4.2.2 on 2023-07-27 16:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0013_alter_presentation_fichier_pptx'),
        ('planning', '0013_room_ip_pc'),
    ]

    operations = [
    ]
