# Generated by Django 4.1.7 on 2023-09-05 14:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('planning', '0014_merge_20230727_1821'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='ip_pc',
        ),
        migrations.AlterField(
            model_name='presentation',
            name='fichier_pptx',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='planning.file'),
        ),
    ]
